workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.app"
      java: 17
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android app
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
